### ISSUE TITLE
help me i have a problem with the last step 

### ISSUE THREAD

**Issue by GHOSTPLAYZ16** [detvnk/youtubeShoutoutWall#1]
i done everything just the last step that doesnt want to work it gives a blank page instead of saying successfully added entry #1

![image](https://user-images.githubusercontent.com/49615102/56094284-18e0b200-5ed3-11e9-8742-5fae8037e9b5.png)

**Comment by detvnk** [comment]
Hi @GHOSTPLAYZ16 I've fixed this issue please download the latest version and follow the updated readme. The !wall custom command now requires a prefix by default it is 'zzz' in the data=zzz$(userid) component. Let me know if you have any issues with this.

**Comment by GHOSTPLAYZ16** [comment]
Thank you but there is another issue... the wall works but .. the only
problem is ..

It says successfully added entry .. but then it doesnt update on the stream
shoutout wall please me .. i redid everything like 2 times and none of that
2 times it worked :)

**Comment by detvnk** [comment]
I've fixed this as of today and committed the fix to the repository.
